// Generated by CoffeeScript 1.3.3
(function() {
  var Frozen, app, express, frzn;

  root._ = require("underscore");

  express = require("express");

  app = express();

  root._utils = require("./lib/utils");

  root.configurator = require("./config/configurator");

  configurator.load();

  root._CNF = configurator.get();

  Frozen = require("./lib/frozen");

  frzn = new Frozen();

  app.use(express.bodyParser());

  app.use(function(err, req, res, next) {
    res.status(500);
    res.render('error', {
      error: err
    });
  });

  require("./lib/routes")(app);

  app.listen(3000);

}).call(this);
