// Generated by CoffeeScript 1.3.3
(function() {
  var Frozen, Glacier, amazon, awssum, glacier, _cred,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  awssum = require("awssum");

  amazon = awssum.load("amazon/amazon");

  Glacier = awssum.load("amazon/glacier").Glacier;

  _cred = _.extend({
    region: amazon[_CNF.region]
  }, _CNF.credentials);

  glacier = new Glacier(_cred);

  module.exports = Frozen = (function() {

    function Frozen() {
      this._convertVaults = __bind(this._convertVaults, this);

      this.getVaults = __bind(this.getVaults, this);
      return;
    }

    Frozen.prototype.getVaults = function(opt, cb) {
      var _this = this;
      glacier.ListVaults(function(err, vaults) {
        if (err) {
          cb(err);
          return;
        }
        return cb(null, _this._convertVaults(vaults));
      });
    };

    Frozen.prototype._convertVaults = function(raw) {
      return raw;
    };

    return Frozen;

  })();

}).call(this);
