// Generated by CoffeeScript 1.3.3
(function() {
  var Glacier, Vaults, amazon, awssum, glacier, _cred;

  awssum = require("awssum");

  Vaults = require("./vaults");

  amazon = awssum.load("amazon/amazon");

  Glacier = awssum.load("amazon/glacier").Glacier;

  _cred = _.extend({
    region: amazon[_CNF.region]
  }, _CNF.credentials);

  glacier = new Glacier(_cred);

  module.exports = function(express) {
    express._apis || (express._apis = {});
    return express._apis = new Vaults(express, glacier);
  };

}).call(this);
